apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoge
  labels:
    app: hoge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hoge
  template:
    metadata:
      labels:
        app: hoge
    spec:
      containers:
      - name: hoge
        image: tacumaigei/hoge:0.0.1
        ports:
        - containerPort: 8080
