apiVersion: v1
kind: Service
metadata:
  name: hoge
  labels:
    run: hoge
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: hoge
